In [1]:
import pandas as pd
df1 = pd.read_csv('AMC/AMC_Monthly_stock_price_5y.csv')
df2 = pd.read_csv('CGX/CGX_Monthly_stock_price_5y.csv')
df3 = pd.read_csv('CNK/CNK_Monthly_stock_price_5y.csv')
display(df1,df2,df3)

,Date,Open,High,Low,Close,Adj Close,Volume,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Company
0,12/1/2018,138.500000,154.399994,116.599998,122.800003,121.678368,2685030,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
1,1/1/2019,120.099998,147.500000,119.000000,146.500000,145.360596,2103930,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
2,2/1/2019,145.199997,145.899994,128.199997,140.300003,139.208817,2658720,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
3,3/1/2019,156.600006,165.000000,141.500000,148.500000,147.345047,4044160,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
4,4/1/2019,149.500000,170.699997,145.300003,151.600006,150.624496,3304970,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
5,5/1/2019,151.500000,153.000000,117.099998,119.800003,119.029114,4136480,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
6,6/1/2019,119.400002,120.800003,92.800003,93.300003,92.699638,4817910,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
7,7/1/2019,98.500000,119.800003,87.300003,118.300003,117.751114,6801140,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
8,8/1/2019,117.000000,124.900002,104.599998,111.099998,110.584526,5908840,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
9,9/1/2019,111.900002,121.300003,104.400002,107.000000,106.503540,3771660,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
10,10/1/2019,107.500000,109.500000,87.800003,93.699997,93.420692,5219300,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
11,11/1/2019,94.500000,103.500000,74.699997,81.800003,81.556168,7752300,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
12,12/1/2019,82.400002,87.800003,71.500000,72.400002,72.355858,7275420,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
13,1/1/2020,73.000000,76.000000,62.500000,65.199997,65.160240,6608580,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
14,2/1/2020,65.000000,77.800003,51.200001,62.599998,62.561829,5801730,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
15,3/1/2020,63.099998,63.200001,19.500000,31.600000,31.580732,12318290,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
16,4/1/2020,30.000000,55.299999,19.500000,49.200001,49.200001,23082170,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
17,5/1/2020,46.200001,64.099998,38.099998,51.299999,51.299999,22659740,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
18,6/1/2020,50.299999,73.500000,37.500000,42.900002,42.900002,17007920,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
19,7/1/2020,42.599998,48.200001,38.099998,40.400002,40.400002,8177990,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
20,8/1/2020,40.500000,71.000000,38.599998,58.799999,58.799999,19674440,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
21,9/1/2020,57.900002,77.099998,43.599998,47.099998,47.099998,14228780,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
22,10/1/2020,47.799999,48.000000,22.799999,23.600000,23.600000,25042970,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
23,11/1/2020,23.000000,50.000000,21.100000,42.700001,42.700001,56334630,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
24,12/1/2020,44.299999,44.299999,20.799999,21.200001,21.200001,61387880,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
25,1/1/2021,22.000000,203.600006,19.100000,132.600006,132.600006,461926050,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
26,2/1/2021,170.000000,172.500000,52.599998,80.099998,80.099998,363385340,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
27,3/1/2021,88.599998,145.399994,75.000000,102.099998,102.099998,247359070,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
28,4/1/2021,102.300003,122.199997,83.099998,100.300003,100.300003,93774920,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
29,5/1/2021,101.099998,367.200012,89.300003,261.200012,261.200012,342906800,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
30,6/1/2021,318.899994,726.200012,285.299988,566.799988,566.799988,552009010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
31,7/1/2021,568.599976,577.099976,311.500000,370.200012,370.200012,207826270,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
32,8/1/2021,375.799988,483.000000,289.100006,471.299988,471.299988,202968870,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
33,9/1/2021,471.600006,527.900024,337.399994,380.600006,380.600006,140000590,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
34,10/1/2021,394.100006,444.399994,345.299988,353.700012,353.700012,81216040,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
35,11/1/2021,356.500000,459.500000,327.500000,339.399994,339.399994,73126990,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
36,12/1/2021,347.100006,349.399994,208.000000,272.000000,272.000000,119254890,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
37,1/1/2022,274.200012,281.299988,134.000000,160.600006,160.600006,96772890,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
38,2/1/2022,181.500000,209.600006,146.500000,188.600006,188.600006,98367720,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
39,3/1/2022,190.000000,343.299988,129.000000,246.399994,246.399994,151744010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
40,4/1/2022,251.300003,252.800003,147.000000,153.000000,153.000000,71012450,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
41,5/1/2022,151.000000,161.300003,97.000000,143.399994,143.399994,106887090,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
42,6/1/2022,140.100006,147.500000,110.900002,135.500000,135.500000,82007240,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
43,7/1/2022,134.800003,183.699997,121.599998,145.600006,145.600006,71300270,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
44,8/1/2022,143.300003,275.000000,86.800003,91.199997,91.199997,144542260,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
45,9/1/2022,90.300003,107.500000,68.099998,69.699997,69.699997,54883410,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
46,10/1/2022,68.400002,81.300003,54.700001,66.599998,66.599998,47378160,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
47,11/1/2022,67.599998,83.500000,50.500000,72.300003,72.300003,55740010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
48,12/1/2022,72.900002,91.500000,38.099998,40.700001,40.700001,66011810,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
49,1/1/2023,41.400002,65.500000,37.700001,53.500000,53.500000,59321450,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
50,2/1/2023,53.000000,85.300003,43.900002,71.400002,71.400002,96052700,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
51,3/1/2023,68.000000,71.099998,40.599998,50.099998,50.099998,64686880,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
52,4/1/2023,49.900002,57.599998,38.799999,55.000000,55.000000,61025520,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
53,5/1/2023,55.299999,61.099998,43.799999,45.000000,45.000000,35134810,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
54,6/1/2023,45.099998,51.500000,40.099998,44.000000,44.000000,36096590,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
55,7/1/2023,43.900002,62.299999,41.700001,49.700001,49.700001,78407850,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
56,8/1/2023,49.299999,54.599998,10.720000,12.550000,12.550000,299686390,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
57,9/1/2023,12.680000,13.760000,7.050000,7.990000,7.990000,560496800,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
58,10/1/2023,8.060000,11.170000,7.730000,10.680000,10.680000,442135100,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC
59,11/1/2023,10.760000,11.430000,7.610000,7.890000,7.890000,257636300,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMC

,Date,Open,High,Low,Close,Adj Close,Volume,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Company
0,12/1/2018,26.070000,26.379999,22.879999,25.440001,23.458450,6076000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
1,1/1/2019,25.389999,28.910000,25.360001,28.440001,26.381290,5194200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
2,2/1/2019,28.389999,28.400000,24.620001,25.670000,23.935223,5715600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
3,3/1/2019,25.790001,26.320000,23.680000,24.340000,22.825405,4773800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
4,4/1/2019,24.450001,25.850000,23.879999,25.620001,24.170401,4300100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
5,5/1/2019,25.620001,26.410000,23.299999,23.350000,22.157042,5738800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
6,6/1/2019,23.410000,24.280001,22.340000,22.990000,21.950487,3531500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
7,7/1/2019,23.020000,24.910000,22.660000,23.700001,22.779373,5829700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
8,8/1/2019,23.680000,25.910000,22.920000,24.799999,23.985315,5208400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
9,9/1/2019,24.709999,26.190001,23.830000,24.260000,23.606178,4760400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
10,10/1/2019,24.280001,24.389999,22.450001,22.450001,21.976290,3142500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
11,11/1/2019,22.639999,26.260000,22.250000,25.389999,25.018272,6637100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
12,12/1/2019,25.320000,34.389999,23.850000,33.849998,33.552242,13305200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
13,1/1/2020,33.820000,34.060001,33.740002,33.770000,33.620842,13355500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
14,2/1/2020,33.759998,33.900002,32.509998,32.990002,32.990002,14674400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
15,3/1/2020,33.150002,33.230000,6.300000,11.700000,11.700000,35131200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
16,4/1/2020,11.750000,16.930000,10.290000,16.639999,16.639999,13400100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
17,5/1/2020,16.040001,16.040001,11.220000,14.550000,14.550000,9391800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
18,6/1/2020,14.500000,16.900000,7.630000,8.040000,8.040000,21932900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
19,7/1/2020,8.480000,9.060000,7.580000,8.000000,8.000000,24134100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
20,8/1/2020,8.050000,10.370000,7.600000,9.900000,9.900000,20412700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
21,9/1/2020,9.940000,10.140000,7.200000,7.210000,7.210000,18005800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
22,10/1/2020,7.240000,7.370000,4.320000,5.090000,5.090000,25530800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
23,11/1/2020,5.070000,11.880000,5.040000,10.400000,10.400000,44729000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
24,12/1/2020,10.650000,11.250000,8.110000,9.270000,9.270000,27932200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
25,1/1/2021,9.270000,12.450000,8.650000,10.500000,10.500000,23813600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
26,2/1/2021,10.580000,14.330000,10.160000,13.820000,13.820000,25602600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
27,3/1/2021,14.240000,15.250000,11.540000,11.910000,11.910000,24300400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
28,4/1/2021,11.950000,13.750000,11.670000,12.700000,12.700000,11617600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
29,5/1/2021,12.730000,16.299999,11.700000,15.700000,15.700000,17115600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
30,6/1/2021,15.980000,16.760000,14.510000,14.900000,14.900000,21336600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
31,7/1/2021,15.050000,16.389999,12.840000,12.920000,12.920000,13763700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
32,8/1/2021,12.780000,14.160000,11.920000,13.140000,13.140000,10240900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
33,9/1/2021,13.150000,13.930000,12.760000,13.140000,13.140000,10949600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
34,10/1/2021,13.150000,14.700000,13.080000,13.260000,13.260000,10032900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
35,11/1/2021,13.310000,15.750000,11.210000,11.720000,11.720000,17063600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
36,12/1/2021,11.950000,14.480000,10.930000,13.610000,13.610000,13572800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
37,1/1/2022,12.960000,13.780000,11.960000,12.970000,12.970000,8628100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
38,2/1/2022,13.000000,13.990000,12.340000,13.840000,13.840000,9274100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
39,3/1/2022,13.840000,14.100000,12.120000,13.410000,13.410000,9287300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
40,4/1/2022,13.460000,13.920000,12.450000,13.160000,13.160000,6320600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
41,5/1/2022,13.000000,13.230000,11.170000,12.910000,12.910000,7080700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
42,6/1/2022,12.950000,13.070000,10.350000,10.810000,10.810000,6675300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
43,7/1/2022,10.850000,11.650000,10.580000,11.220000,11.220000,4917800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
44,8/1/2022,11.130000,12.230000,8.890000,9.010000,9.010000,8476900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
45,9/1/2022,8.950000,9.830000,8.120000,9.100000,9.100000,6448000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
46,10/1/2022,9.130000,9.380000,8.180000,9.260000,9.260000,4973200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
47,11/1/2022,9.400000,10.830000,9.120000,10.300000,10.300000,5673600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
48,12/1/2022,10.280000,10.450000,7.300000,8.050000,8.050000,6155800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
49,1/1/2023,8.070000,8.780000,7.620000,8.740000,8.740000,7647800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
50,2/1/2023,8.730000,9.410000,8.060000,8.220000,8.220000,6510000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
51,3/1/2023,8.190000,8.970000,7.480000,8.830000,8.830000,6529200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
52,4/1/2023,8.830000,9.500000,8.420000,8.880000,8.880000,4195300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
53,5/1/2023,8.800000,10.260000,8.300000,9.780000,9.780000,7987000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
54,6/1/2023,9.780000,9.970000,8.620000,8.870000,8.870000,3834400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
55,7/1/2023,8.900000,9.460000,8.810000,9.200000,9.200000,5043700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
56,8/1/2023,9.150000,9.760000,7.920000,8.540000,8.540000,8556200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
57,9/1/2023,8.550000,9.700000,7.850000,9.470000,9.470000,7545900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
58,10/1/2023,9.470000,9.560000,7.880000,8.340000,8.340000,5040400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX
59,11/1/2023,8.300000,9.640000,8.300000,9.160000,9.160000,5701700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CGX

,Date,Open,High,Low,Close,Adj Close,Volume,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Company
0,12/1/2018,26.070000,26.379999,22.879999,25.440001,23.458450,6076000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
1,1/1/2019,25.389999,28.910000,25.360001,28.440001,26.381290,5194200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
2,2/1/2019,28.389999,28.400000,24.620001,25.670000,23.935223,5715600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
3,3/1/2019,25.790001,26.320000,23.680000,24.340000,22.825405,4773800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
4,4/1/2019,24.450001,25.850000,23.879999,25.620001,24.170401,4300100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
5,5/1/2019,25.620001,26.410000,23.299999,23.350000,22.157042,5738800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
6,6/1/2019,23.410000,24.280001,22.340000,22.990000,21.950487,3531500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
7,7/1/2019,23.020000,24.910000,22.660000,23.700001,22.779373,5829700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
8,8/1/2019,23.680000,25.910000,22.920000,24.799999,23.985315,5208400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
9,9/1/2019,24.709999,26.190001,23.830000,24.260000,23.606178,4760400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
10,10/1/2019,24.280001,24.389999,22.450001,22.450001,21.976290,3142500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
11,11/1/2019,22.639999,26.260000,22.250000,25.389999,25.018272,6637100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
12,12/1/2019,25.320000,34.389999,23.850000,33.849998,33.552242,13305200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
13,1/1/2020,33.820000,34.060001,33.740002,33.770000,33.620842,13355500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
14,2/1/2020,33.759998,33.900002,32.509998,32.990002,32.990002,14674400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
15,3/1/2020,33.150002,33.230000,6.300000,11.700000,11.700000,35131200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
16,4/1/2020,11.750000,16.930000,10.290000,16.639999,16.639999,13400100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
17,5/1/2020,16.040001,16.040001,11.220000,14.550000,14.550000,9391800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
18,6/1/2020,14.500000,16.900000,7.630000,8.040000,8.040000,21932900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
19,7/1/2020,8.480000,9.060000,7.580000,8.000000,8.000000,24134100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
20,8/1/2020,8.050000,10.370000,7.600000,9.900000,9.900000,20412700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
21,9/1/2020,9.940000,10.140000,7.200000,7.210000,7.210000,18005800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
22,10/1/2020,7.240000,7.370000,4.320000,5.090000,5.090000,25530800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
23,11/1/2020,5.070000,11.880000,5.040000,10.400000,10.400000,44729000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
24,12/1/2020,10.650000,11.250000,8.110000,9.270000,9.270000,27932200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
25,1/1/2021,9.270000,12.450000,8.650000,10.500000,10.500000,23813600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
26,2/1/2021,10.580000,14.330000,10.160000,13.820000,13.820000,25602600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
27,3/1/2021,14.240000,15.250000,11.540000,11.910000,11.910000,24300400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
28,4/1/2021,11.950000,13.750000,11.670000,12.700000,12.700000,11617600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
29,5/1/2021,12.730000,16.299999,11.700000,15.700000,15.700000,17115600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
30,6/1/2021,15.980000,16.760000,14.510000,14.900000,14.900000,21336600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
31,7/1/2021,15.050000,16.389999,12.840000,12.920000,12.920000,13763700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
32,8/1/2021,12.780000,14.160000,11.920000,13.140000,13.140000,10240900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
33,9/1/2021,13.150000,13.930000,12.760000,13.140000,13.140000,10949600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
34,10/1/2021,13.150000,14.700000,13.080000,13.260000,13.260000,10032900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
35,11/1/2021,13.310000,15.750000,11.210000,11.720000,11.720000,17063600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
36,12/1/2021,11.950000,14.480000,10.930000,13.610000,13.610000,13572800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
37,1/1/2022,12.960000,13.780000,11.960000,12.970000,12.970000,8628100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
38,2/1/2022,13.000000,13.990000,12.340000,13.840000,13.840000,9274100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
39,3/1/2022,13.840000,14.100000,12.120000,13.410000,13.410000,9287300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
40,4/1/2022,13.460000,13.920000,12.450000,13.160000,13.160000,6320600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
41,5/1/2022,13.000000,13.230000,11.170000,12.910000,12.910000,7080700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
42,6/1/2022,12.950000,13.070000,10.350000,10.810000,10.810000,6675300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
43,7/1/2022,10.850000,11.650000,10.580000,11.220000,11.220000,4917800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
44,8/1/2022,11.130000,12.230000,8.890000,9.010000,9.010000,8476900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
45,9/1/2022,8.950000,9.830000,8.120000,9.100000,9.100000,6448000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
46,10/1/2022,9.130000,9.380000,8.180000,9.260000,9.260000,4973200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
47,11/1/2022,9.400000,10.830000,9.120000,10.300000,10.300000,5673600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
48,12/1/2022,10.280000,10.450000,7.300000,8.050000,8.050000,6155800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
49,1/1/2023,8.070000,8.780000,7.620000,8.740000,8.740000,7647800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
50,2/1/2023,8.730000,9.410000,8.060000,8.220000,8.220000,6510000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
51,3/1/2023,8.190000,8.970000,7.480000,8.830000,8.830000,6529200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
52,4/1/2023,8.830000,9.500000,8.420000,8.880000,8.880000,4195300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
53,5/1/2023,8.800000,10.260000,8.300000,9.780000,9.780000,7987000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
54,6/1/2023,9.780000,9.970000,8.620000,8.870000,8.870000,3834400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
55,7/1/2023,8.900000,9.460000,8.810000,9.200000,9.200000,5043700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
56,8/1/2023,9.150000,9.760000,7.920000,8.540000,8.540000,8556200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
57,9/1/2023,8.550000,9.700000,7.850000,9.470000,9.470000,7545900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
58,10/1/2023,9.470000,9.560000,7.880000,8.340000,8.340000,5040400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK
59,11/1/2023,8.300000,9.640000,8.300000,9.160000,9.160000,5701700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CNK

In [2]:

# Function to process each DataFrame
def process_unnamed_columns(df):
    # List of columns in the DataFrame
    existing_columns = df.columns

    # List of columns to drop
    cols_to_drop = [col for col in existing_columns if 'Unnamed' in col]

    # Checking if each column exists before dropping
    for col in cols_to_drop:
        if col in existing_columns:
            df.drop(col, axis=1, inplace=True)

# Apply the function to each DataFrame
process_unnamed_columns(df1)
process_unnamed_columns(df2)
process_unnamed_columns(df3)

# Display the DataFrames after processing
display(df1,df2,df3)

,Date,Open,High,Low,Close,Adj Close,Volume,Company
0,12/1/2018,138.500000,154.399994,116.599998,122.800003,121.678368,2685030,AMC
1,1/1/2019,120.099998,147.500000,119.000000,146.500000,145.360596,2103930,AMC
2,2/1/2019,145.199997,145.899994,128.199997,140.300003,139.208817,2658720,AMC
3,3/1/2019,156.600006,165.000000,141.500000,148.500000,147.345047,4044160,AMC
4,4/1/2019,149.500000,170.699997,145.300003,151.600006,150.624496,3304970,AMC
5,5/1/2019,151.500000,153.000000,117.099998,119.800003,119.029114,4136480,AMC
6,6/1/2019,119.400002,120.800003,92.800003,93.300003,92.699638,4817910,AMC
7,7/1/2019,98.500000,119.800003,87.300003,118.300003,117.751114,6801140,AMC
8,8/1/2019,117.000000,124.900002,104.599998,111.099998,110.584526,5908840,AMC
9,9/1/2019,111.900002,121.300003,104.400002,107.000000,106.503540,3771660,AMC
10,10/1/2019,107.500000,109.500000,87.800003,93.699997,93.420692,5219300,AMC
11,11/1/2019,94.500000,103.500000,74.699997,81.800003,81.556168,7752300,AMC
12,12/1/2019,82.400002,87.800003,71.500000,72.400002,72.355858,7275420,AMC
13,1/1/2020,73.000000,76.000000,62.500000,65.199997,65.160240,6608580,AMC
14,2/1/2020,65.000000,77.800003,51.200001,62.599998,62.561829,5801730,AMC
15,3/1/2020,63.099998,63.200001,19.500000,31.600000,31.580732,12318290,AMC
16,4/1/2020,30.000000,55.299999,19.500000,49.200001,49.200001,23082170,AMC
17,5/1/2020,46.200001,64.099998,38.099998,51.299999,51.299999,22659740,AMC
18,6/1/2020,50.299999,73.500000,37.500000,42.900002,42.900002,17007920,AMC
19,7/1/2020,42.599998,48.200001,38.099998,40.400002,40.400002,8177990,AMC
20,8/1/2020,40.500000,71.000000,38.599998,58.799999,58.799999,19674440,AMC
21,9/1/2020,57.900002,77.099998,43.599998,47.099998,47.099998,14228780,AMC
22,10/1/2020,47.799999,48.000000,22.799999,23.600000,23.600000,25042970,AMC
23,11/1/2020,23.000000,50.000000,21.100000,42.700001,42.700001,56334630,AMC
24,12/1/2020,44.299999,44.299999,20.799999,21.200001,21.200001,61387880,AMC
25,1/1/2021,22.000000,203.600006,19.100000,132.600006,132.600006,461926050,AMC
26,2/1/2021,170.000000,172.500000,52.599998,80.099998,80.099998,363385340,AMC
27,3/1/2021,88.599998,145.399994,75.000000,102.099998,102.099998,247359070,AMC
28,4/1/2021,102.300003,122.199997,83.099998,100.300003,100.300003,93774920,AMC
29,5/1/2021,101.099998,367.200012,89.300003,261.200012,261.200012,342906800,AMC
30,6/1/2021,318.899994,726.200012,285.299988,566.799988,566.799988,552009010,AMC
31,7/1/2021,568.599976,577.099976,311.500000,370.200012,370.200012,207826270,AMC
32,8/1/2021,375.799988,483.000000,289.100006,471.299988,471.299988,202968870,AMC
33,9/1/2021,471.600006,527.900024,337.399994,380.600006,380.600006,140000590,AMC
34,10/1/2021,394.100006,444.399994,345.299988,353.700012,353.700012,81216040,AMC
35,11/1/2021,356.500000,459.500000,327.500000,339.399994,339.399994,73126990,AMC
36,12/1/2021,347.100006,349.399994,208.000000,272.000000,272.000000,119254890,AMC
37,1/1/2022,274.200012,281.299988,134.000000,160.600006,160.600006,96772890,AMC
38,2/1/2022,181.500000,209.600006,146.500000,188.600006,188.600006,98367720,AMC
39,3/1/2022,190.000000,343.299988,129.000000,246.399994,246.399994,151744010,AMC
40,4/1/2022,251.300003,252.800003,147.000000,153.000000,153.000000,71012450,AMC
41,5/1/2022,151.000000,161.300003,97.000000,143.399994,143.399994,106887090,AMC
42,6/1/2022,140.100006,147.500000,110.900002,135.500000,135.500000,82007240,AMC
43,7/1/2022,134.800003,183.699997,121.599998,145.600006,145.600006,71300270,AMC
44,8/1/2022,143.300003,275.000000,86.800003,91.199997,91.199997,144542260,AMC
45,9/1/2022,90.300003,107.500000,68.099998,69.699997,69.699997,54883410,AMC
46,10/1/2022,68.400002,81.300003,54.700001,66.599998,66.599998,47378160,AMC
47,11/1/2022,67.599998,83.500000,50.500000,72.300003,72.300003,55740010,AMC
48,12/1/2022,72.900002,91.500000,38.099998,40.700001,40.700001,66011810,AMC
49,1/1/2023,41.400002,65.500000,37.700001,53.500000,53.500000,59321450,AMC
50,2/1/2023,53.000000,85.300003,43.900002,71.400002,71.400002,96052700,AMC
51,3/1/2023,68.000000,71.099998,40.599998,50.099998,50.099998,64686880,AMC
52,4/1/2023,49.900002,57.599998,38.799999,55.000000,55.000000,61025520,AMC
53,5/1/2023,55.299999,61.099998,43.799999,45.000000,45.000000,35134810,AMC
54,6/1/2023,45.099998,51.500000,40.099998,44.000000,44.000000,36096590,AMC
55,7/1/2023,43.900002,62.299999,41.700001,49.700001,49.700001,78407850,AMC
56,8/1/2023,49.299999,54.599998,10.720000,12.550000,12.550000,299686390,AMC
57,9/1/2023,12.680000,13.760000,7.050000,7.990000,7.990000,560496800,AMC
58,10/1/2023,8.060000,11.170000,7.730000,10.680000,10.680000,442135100,AMC
59,11/1/2023,10.760000,11.430000,7.610000,7.890000,7.890000,257636300,AMC

,Date,Open,High,Low,Close,Adj Close,Volume,Company
0,12/1/2018,26.070000,26.379999,22.879999,25.440001,23.458450,6076000,CGX
1,1/1/2019,25.389999,28.910000,25.360001,28.440001,26.381290,5194200,CGX
2,2/1/2019,28.389999,28.400000,24.620001,25.670000,23.935223,5715600,CGX
3,3/1/2019,25.790001,26.320000,23.680000,24.340000,22.825405,4773800,CGX
4,4/1/2019,24.450001,25.850000,23.879999,25.620001,24.170401,4300100,CGX
5,5/1/2019,25.620001,26.410000,23.299999,23.350000,22.157042,5738800,CGX
6,6/1/2019,23.410000,24.280001,22.340000,22.990000,21.950487,3531500,CGX
7,7/1/2019,23.020000,24.910000,22.660000,23.700001,22.779373,5829700,CGX
8,8/1/2019,23.680000,25.910000,22.920000,24.799999,23.985315,5208400,CGX
9,9/1/2019,24.709999,26.190001,23.830000,24.260000,23.606178,4760400,CGX
10,10/1/2019,24.280001,24.389999,22.450001,22.450001,21.976290,3142500,CGX
11,11/1/2019,22.639999,26.260000,22.250000,25.389999,25.018272,6637100,CGX
12,12/1/2019,25.320000,34.389999,23.850000,33.849998,33.552242,13305200,CGX
13,1/1/2020,33.820000,34.060001,33.740002,33.770000,33.620842,13355500,CGX
14,2/1/2020,33.759998,33.900002,32.509998,32.990002,32.990002,14674400,CGX
15,3/1/2020,33.150002,33.230000,6.300000,11.700000,11.700000,35131200,CGX
16,4/1/2020,11.750000,16.930000,10.290000,16.639999,16.639999,13400100,CGX
17,5/1/2020,16.040001,16.040001,11.220000,14.550000,14.550000,9391800,CGX
18,6/1/2020,14.500000,16.900000,7.630000,8.040000,8.040000,21932900,CGX
19,7/1/2020,8.480000,9.060000,7.580000,8.000000,8.000000,24134100,CGX
20,8/1/2020,8.050000,10.370000,7.600000,9.900000,9.900000,20412700,CGX
21,9/1/2020,9.940000,10.140000,7.200000,7.210000,7.210000,18005800,CGX
22,10/1/2020,7.240000,7.370000,4.320000,5.090000,5.090000,25530800,CGX
23,11/1/2020,5.070000,11.880000,5.040000,10.400000,10.400000,44729000,CGX
24,12/1/2020,10.650000,11.250000,8.110000,9.270000,9.270000,27932200,CGX
25,1/1/2021,9.270000,12.450000,8.650000,10.500000,10.500000,23813600,CGX
26,2/1/2021,10.580000,14.330000,10.160000,13.820000,13.820000,25602600,CGX
27,3/1/2021,14.240000,15.250000,11.540000,11.910000,11.910000,24300400,CGX
28,4/1/2021,11.950000,13.750000,11.670000,12.700000,12.700000,11617600,CGX
29,5/1/2021,12.730000,16.299999,11.700000,15.700000,15.700000,17115600,CGX
30,6/1/2021,15.980000,16.760000,14.510000,14.900000,14.900000,21336600,CGX
31,7/1/2021,15.050000,16.389999,12.840000,12.920000,12.920000,13763700,CGX
32,8/1/2021,12.780000,14.160000,11.920000,13.140000,13.140000,10240900,CGX
33,9/1/2021,13.150000,13.930000,12.760000,13.140000,13.140000,10949600,CGX
34,10/1/2021,13.150000,14.700000,13.080000,13.260000,13.260000,10032900,CGX
35,11/1/2021,13.310000,15.750000,11.210000,11.720000,11.720000,17063600,CGX
36,12/1/2021,11.950000,14.480000,10.930000,13.610000,13.610000,13572800,CGX
37,1/1/2022,12.960000,13.780000,11.960000,12.970000,12.970000,8628100,CGX
38,2/1/2022,13.000000,13.990000,12.340000,13.840000,13.840000,9274100,CGX
39,3/1/2022,13.840000,14.100000,12.120000,13.410000,13.410000,9287300,CGX
40,4/1/2022,13.460000,13.920000,12.450000,13.160000,13.160000,6320600,CGX
41,5/1/2022,13.000000,13.230000,11.170000,12.910000,12.910000,7080700,CGX
42,6/1/2022,12.950000,13.070000,10.350000,10.810000,10.810000,6675300,CGX
43,7/1/2022,10.850000,11.650000,10.580000,11.220000,11.220000,4917800,CGX
44,8/1/2022,11.130000,12.230000,8.890000,9.010000,9.010000,8476900,CGX
45,9/1/2022,8.950000,9.830000,8.120000,9.100000,9.100000,6448000,CGX
46,10/1/2022,9.130000,9.380000,8.180000,9.260000,9.260000,4973200,CGX
47,11/1/2022,9.400000,10.830000,9.120000,10.300000,10.300000,5673600,CGX
48,12/1/2022,10.280000,10.450000,7.300000,8.050000,8.050000,6155800,CGX
49,1/1/2023,8.070000,8.780000,7.620000,8.740000,8.740000,7647800,CGX
50,2/1/2023,8.730000,9.410000,8.060000,8.220000,8.220000,6510000,CGX
51,3/1/2023,8.190000,8.970000,7.480000,8.830000,8.830000,6529200,CGX
52,4/1/2023,8.830000,9.500000,8.420000,8.880000,8.880000,4195300,CGX
53,5/1/2023,8.800000,10.260000,8.300000,9.780000,9.780000,7987000,CGX
54,6/1/2023,9.780000,9.970000,8.620000,8.870000,8.870000,3834400,CGX
55,7/1/2023,8.900000,9.460000,8.810000,9.200000,9.200000,5043700,CGX
56,8/1/2023,9.150000,9.760000,7.920000,8.540000,8.540000,8556200,CGX
57,9/1/2023,8.550000,9.700000,7.850000,9.470000,9.470000,7545900,CGX
58,10/1/2023,9.470000,9.560000,7.880000,8.340000,8.340000,5040400,CGX
59,11/1/2023,8.300000,9.640000,8.300000,9.160000,9.160000,5701700,CGX

,Date,Open,High,Low,Close,Adj Close,Volume,Company
0,12/1/2018,26.070000,26.379999,22.879999,25.440001,23.458450,6076000,CNK
1,1/1/2019,25.389999,28.910000,25.360001,28.440001,26.381290,5194200,CNK
2,2/1/2019,28.389999,28.400000,24.620001,25.670000,23.935223,5715600,CNK
3,3/1/2019,25.790001,26.320000,23.680000,24.340000,22.825405,4773800,CNK
4,4/1/2019,24.450001,25.850000,23.879999,25.620001,24.170401,4300100,CNK
5,5/1/2019,25.620001,26.410000,23.299999,23.350000,22.157042,5738800,CNK
6,6/1/2019,23.410000,24.280001,22.340000,22.990000,21.950487,3531500,CNK
7,7/1/2019,23.020000,24.910000,22.660000,23.700001,22.779373,5829700,CNK
8,8/1/2019,23.680000,25.910000,22.920000,24.799999,23.985315,5208400,CNK
9,9/1/2019,24.709999,26.190001,23.830000,24.260000,23.606178,4760400,CNK
10,10/1/2019,24.280001,24.389999,22.450001,22.450001,21.976290,3142500,CNK
11,11/1/2019,22.639999,26.260000,22.250000,25.389999,25.018272,6637100,CNK
12,12/1/2019,25.320000,34.389999,23.850000,33.849998,33.552242,13305200,CNK
13,1/1/2020,33.820000,34.060001,33.740002,33.770000,33.620842,13355500,CNK
14,2/1/2020,33.759998,33.900002,32.509998,32.990002,32.990002,14674400,CNK
15,3/1/2020,33.150002,33.230000,6.300000,11.700000,11.700000,35131200,CNK
16,4/1/2020,11.750000,16.930000,10.290000,16.639999,16.639999,13400100,CNK
17,5/1/2020,16.040001,16.040001,11.220000,14.550000,14.550000,9391800,CNK
18,6/1/2020,14.500000,16.900000,7.630000,8.040000,8.040000,21932900,CNK
19,7/1/2020,8.480000,9.060000,7.580000,8.000000,8.000000,24134100,CNK
20,8/1/2020,8.050000,10.370000,7.600000,9.900000,9.900000,20412700,CNK
21,9/1/2020,9.940000,10.140000,7.200000,7.210000,7.210000,18005800,CNK
22,10/1/2020,7.240000,7.370000,4.320000,5.090000,5.090000,25530800,CNK
23,11/1/2020,5.070000,11.880000,5.040000,10.400000,10.400000,44729000,CNK
24,12/1/2020,10.650000,11.250000,8.110000,9.270000,9.270000,27932200,CNK
25,1/1/2021,9.270000,12.450000,8.650000,10.500000,10.500000,23813600,CNK
26,2/1/2021,10.580000,14.330000,10.160000,13.820000,13.820000,25602600,CNK
27,3/1/2021,14.240000,15.250000,11.540000,11.910000,11.910000,24300400,CNK
28,4/1/2021,11.950000,13.750000,11.670000,12.700000,12.700000,11617600,CNK
29,5/1/2021,12.730000,16.299999,11.700000,15.700000,15.700000,17115600,CNK
30,6/1/2021,15.980000,16.760000,14.510000,14.900000,14.900000,21336600,CNK
31,7/1/2021,15.050000,16.389999,12.840000,12.920000,12.920000,13763700,CNK
32,8/1/2021,12.780000,14.160000,11.920000,13.140000,13.140000,10240900,CNK
33,9/1/2021,13.150000,13.930000,12.760000,13.140000,13.140000,10949600,CNK
34,10/1/2021,13.150000,14.700000,13.080000,13.260000,13.260000,10032900,CNK
35,11/1/2021,13.310000,15.750000,11.210000,11.720000,11.720000,17063600,CNK
36,12/1/2021,11.950000,14.480000,10.930000,13.610000,13.610000,13572800,CNK
37,1/1/2022,12.960000,13.780000,11.960000,12.970000,12.970000,8628100,CNK
38,2/1/2022,13.000000,13.990000,12.340000,13.840000,13.840000,9274100,CNK
39,3/1/2022,13.840000,14.100000,12.120000,13.410000,13.410000,9287300,CNK
40,4/1/2022,13.460000,13.920000,12.450000,13.160000,13.160000,6320600,CNK
41,5/1/2022,13.000000,13.230000,11.170000,12.910000,12.910000,7080700,CNK
42,6/1/2022,12.950000,13.070000,10.350000,10.810000,10.810000,6675300,CNK
43,7/1/2022,10.850000,11.650000,10.580000,11.220000,11.220000,4917800,CNK
44,8/1/2022,11.130000,12.230000,8.890000,9.010000,9.010000,8476900,CNK
45,9/1/2022,8.950000,9.830000,8.120000,9.100000,9.100000,6448000,CNK
46,10/1/2022,9.130000,9.380000,8.180000,9.260000,9.260000,4973200,CNK
47,11/1/2022,9.400000,10.830000,9.120000,10.300000,10.300000,5673600,CNK
48,12/1/2022,10.280000,10.450000,7.300000,8.050000,8.050000,6155800,CNK
49,1/1/2023,8.070000,8.780000,7.620000,8.740000,8.740000,7647800,CNK
50,2/1/2023,8.730000,9.410000,8.060000,8.220000,8.220000,6510000,CNK
51,3/1/2023,8.190000,8.970000,7.480000,8.830000,8.830000,6529200,CNK
52,4/1/2023,8.830000,9.500000,8.420000,8.880000,8.880000,4195300,CNK
53,5/1/2023,8.800000,10.260000,8.300000,9.780000,9.780000,7987000,CNK
54,6/1/2023,9.780000,9.970000,8.620000,8.870000,8.870000,3834400,CNK
55,7/1/2023,8.900000,9.460000,8.810000,9.200000,9.200000,5043700,CNK
56,8/1/2023,9.150000,9.760000,7.920000,8.540000,8.540000,8556200,CNK
57,9/1/2023,8.550000,9.700000,7.850000,9.470000,9.470000,7545900,CNK
58,10/1/2023,9.470000,9.560000,7.880000,8.340000,8.340000,5040400,CNK
59,11/1/2023,8.300000,9.640000,8.300000,9.160000,9.160000,5701700,CNK

In [6]:
import pandas as pd

def process_conversion(df, conversion_factor, columns_to_convert):
    for col in columns_to_convert:
        # Convert to numeric, multiply by conversion factor, and round to the nearest hundredth
        df[col] = (pd.to_numeric(df[col], errors='coerce') * conversion_factor).round(2)
    return df

# Load data from CSV
df2 = pd.read_csv('CGX/CGX_Monthly_stock_price_5y.csv')

# Define the conversion factor (CAD to USD)
conversion_factor = 0.729041  # As per the exchange rate provided

# Specify the columns to convert
columns_to_convert = ['Open', 'High', 'Low', 'Close', 'Adj Close']

# Apply the conversion
df2 = process_conversion(df2, conversion_factor, columns_to_convert)

# Save the modified DataFrame back to CSV
df2.to_csv('CGX/CGX_Monthly_stock_price_5y_converted.csv', index=False)

print(df2.head())

        Date   Open   High    Low  Close  Adj Close   Volume Company
0  12/1/2018  19.01  19.23  16.68  18.55      17.10  6076000     CGX
1   1/1/2019  18.51  21.08  18.49  20.73      19.23  5194200     CGX
2   2/1/2019  20.70  20.70  17.95  18.71      17.45  5715600     CGX
3   3/1/2019  18.80  19.19  17.26  17.74      16.64  4773800     CGX
4   4/1/2019  17.83  18.85  17.41  18.68      17.62  4300100     CGX

In [1]:
import pandas as pd

def process_conversion(df, conversion_factor, columns_to_convert):
    for col in columns_to_convert:
        df[col] = pd.to_numeric(df[col], errors='coerce') / conversion_factor
    return df

# Load data from CSV
df1 = pd.read_csv('AMC/AMC_Monthly_stock_price_5y.csv')

# Define the conversion factor
conversion_factor = 10

# Specify the columns to convert
columns_to_convert = ['Open', 'High', 'Low', 'Close', 'Adj Close']

# Apply the conversion
df1 = process_conversion(df1, conversion_factor, columns_to_convert)

# Save the modified DataFrame back to CSV
df1.to_csv('AMC/AMC_Monthly_stock_price_5y_converted.csv', index=False)

print(df1.head())

        Date       Open       High    Low      Close  Adj Close   Volume  \
0  12/1/2018  13.850000  15.439999  11.66  12.280000  12.167837  2685030
1   1/1/2019  12.010000  14.750000  11.90  14.650000  14.536060  2103930
2   2/1/2019  14.520000  14.589999  12.82  14.030000  13.920882  2658720
3   3/1/2019  15.660001  16.500000  14.15  14.850000  14.734505  4044160
4   4/1/2019  14.950000  17.070000  14.53  15.160001  15.062450  3304970

  Company
0     AMC
1     AMC
2     AMC
3     AMC
4     AMC

In [9]:
# Add the company identifier
import pandas as pd
df1 = pd.read_csv('AMC/AMC_Monthly_stock_price_5y.csv')
df2 = pd.read_csv('CGX/CGX_Monthly_stock_price_5y.csv')
df3 = pd.read_csv('CNK/CNK_Monthly_stock_price_5y.csv')
df1['Company'] = 'AMC'
df2['Company'] = 'CGX'
df3['Company'] = 'CNK'

In [2]:
import pandas as pd
df1 = pd.read_csv('AMC/AMC_Monthly_stock_price_5y.csv')
df2 = pd.read_csv('CGX/CGX_Monthly_stock_price_5y.csv')
df3 = pd.read_csv('CNK/CNK_Monthly_stock_price_5y.csv')

# Load the existing data
df1_existing = pd.read_csv('AMC/AMC_Monthly_stock_price_5y.csv')
df2_existing = pd.read_csv('CGX/CGX_Monthly_stock_price_5y.csv')
df3_existing = pd.read_csv('CNK/CNK_Monthly_stock_price_5y.csv')

# Save the new data to replace the existing files
df1.to_csv('AMC/AMC_Monthly_stock_price_5y.csv', index=False)
df2.to_csv('CGX/CGX_Monthly_stock_price_5y.csv', index=False)
df3.to_csv('CNK/CNK_Monthly_stock_price_5y.csv', index=False)